apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-ds
  labels:
    app: dev
spec:
  selector:
    matchLabels: 
      app: nginx_1
  template:
    metadata:
      name: DemonSet-pod
      labels:
        app: nginx_1
    spec:
      containers:
      - name: mynginx
        image: nginx
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
    
      
