apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: Sridhar
spec:
  containers:
  - name: nginx-pod
    image: nginx
    imagePullPolicy: Always
    env:
      - name: Environment
        value: "Dev"
    resources:
      requests: # sets the minimum amount of RAM or CPU required for the container. Importent at schedule time
        memory: "6Mi" #Mi stands for mebibytes 1Mi = 1048.58 kb
        cpu: "100m" # 1CPU = 1vCPU/Core
      limits: # sets the minimum amount of RAM or CPU required for the container. Important at run time
        memory: "12Mi" # ram
        cpu: "5" # m = millicpu = millicores
    ports:
      - containerPort: 80
  affinity:  # defining affinity # works with multiple lables.
    nodeAffinity: # defining nodeAffinity
      requiredDuringSchedulingIgnoredDuringExecution:  # hardRule - requirement should match to get pod created
        nodeSelectorTerms: 
         - matchExpressions:
            - key: zone
              operator: In
              values:
                - us-east-1
                - eu-west-1
      preferredDuringSchedulingIgnoredDuringExecution: # softRule - its optional 
        - weight: 1 # lower value get high priority 
          preference:
            matchExpressions:
              - key: drbackup
                operator: In
                values:
                  - europe
          



# https://signoz.io/blog/kubectl-top/ - understanding more about memory and cpu
