apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
  #namespace: development
  #annotations:
   # cloud.google.com/load-balancer-type: "Internal" # to route traffic from Services inside the same virtual network 
  labels:
    env: dev

spec:
  selector:
    app: nginx_1 # labels given to a pod
                  # only one selector works at a time
  ports:
    - name: http
      port: 80  # port on which service listen to [can be changed]
      targetPort: 80 # Target port on which actual app is listening [Fixed]
      protocol: TCP
  # loadBalancerIP: 10.80.0.212 # range is CNI range
  type: LoadBalancer # Type of service [ClusterIP,NodePort , LoadBalancer]

    

